[package]
name = "rsdk_mod_manager_rs"
version = "1.1.0"
edition = "2024"
description = "Manage mods for RSDK games"

[dependencies]
env_logger = "0.11.11"
eframe = "0.34.3"
egui_extras = "0.34.3"
rust-ini = "0.21.3"
native-dialog = "0.9.7"
egui = "0.34.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
archive = "0.3.2"
reqwest = { version = "0.13.4", features = ["stream"] }
tokio = { version = "1.53.1", features = ["full"] }
futures-util = "0.3.34"
egui-async = "0.4.1"
dirs = "6.0.0"

[target.'cfg(windows)'.dependencies]
windows-registry = "0.6.1"

[package.metadata.bundle]
name = "RSDK Mod Manager"
identifier = "com.mariomastr.rsdk_mod_manager"
icon = ["icons/icon.icns"]
version = "1.1.0"
copyright = "Copyright © 2026"
linux_mime_types = ["x-scheme-handler/s1mm", "x-scheme-handler/s2mm", "x-scheme-handler/scdmm", "x-scheme-handler/smmm"]
linux_exec_args = "%u"
osx_url_schemes = ["s1mm", "s2mm", "scdmm", "smmm"]
