[package]
name = "rsdk_mod_manager_rs"
version = "1.1.0"
edition = "2024"
description = "Manage mods for RSDK games"

[dependencies]
env_logger = "0.11.11"
eframe = "0.34.3"
egui_extras = "0.34.3"
rust-ini = "0.21.3"
native-dialog = "0.9.7"
egui = "0.34.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
archive = "0.3.2"
reqwest = { version = "0.13.4", features = ["stream"] }
tokio = { version = "1.53.1", features = ["full"] }
futures-util = "0.3.34"
egui-async = "0.4.1"
dirs = "6.0.0"

[target.'cfg(windows)'.dependencies]
windows-registry = "0.6.1"

[package.metadata.packager]
product_name = "RSDK Mod Manager"
version = "1.1.0"
binaries = [ { main = true, path = "rsdk_mod_manager_rs" } ]
out-dir = "dist"
identifier = "com.mariomastr.rsdk_mod_manager"
before_packaging_command = "cargo build --release"
formats = ["wix", "dmg", "appimage"]
description = "Manage mods for RSDK games"
icons = ["icons/icon-16x16.png", "icons/icon-24x24.png", "icons/icon-32x32.png", "icons/icon-48x48.png", "icons/icon-64x64.png", "icons/icon-128x128.png", "icons/icon-256x256.png", "icons/icon.ico", "icons/icon.icns"]
deep_link_protocols = [{schemes = ["s1mm", "s2mm", "scdmm", "smmm"], name = "RSDK Mod Manager", role = "shell"}]
