[package]
name = "rsdk_mod_manager_rs"
version = "0.1.0"
edition = "2024"
description = "Manage mods for RSDK games"

[dependencies]
env_logger = "0.11.8"
eframe = "0.34.2"
egui_extras = "0.34.2"
rust-ini = "0.21.3"
native-dialog = "0.9.6"
egui = "0.34.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
archive = "0.3.0"
reqwest = { version = "0.13.3", features = ["stream"] }
tokio = { version = "1.52.3", features = ["full"] }
futures-util = "0.3.32"
egui-async = "0.4.1"
registry = "1.3.0"
dirs = "6.0.0"

[package.metadata.bundle]
name = "RSDK Mod Manager"
identifier = "com.mariomastr.rsdk_mod_manager"
icon = ["icons/icon.icns"]
version = "0.1.0"
copyright = "Copyright © 2026"
linux_mime_types = ["s1mm", "s2mm", "scdmm", "smmm"]
osx_url_schemes = ["s1mm", "s2mm", "scdmm", "smmm"]
