on:
  workflow_dispatch:
  push:
    branches:
      - "**"

name: Build RSDK Mod Manager

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: x86_64-pc-windows-msvc
          path: "/Users/runner/work/rsdk_mod_manager_rs/rsdk_mod_manager_rs/target/x86_64-pc-windows-msvc/release/rsdk_mod_manager_rs.exe"

        - name: macOS arm64
          os: macos-latest
          target: aarch64-apple-darwin
          path: "/Users/runner/work/rsdk_mod_manager_rs/rsdk_mod_manager_rs/target/aarch64-apple-darwin/release/bundle/osx/RSDK Mod Manager.app"

        - name: macOS x86_64
          os: macos-latest
          target: x86_64-apple-darwin
          path: "/Users/runner/work/rsdk_mod_manager_rs/rsdk_mod_manager_rs/target/x86_64-apple-darwin/release/bundle/osx/RSDK Mod Manager.app"

        - name: Linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          path: "/home/runner/work/rsdk_mod_manager_rs/rsdk_mod_manager_rs/target/x86_64-unknown-linux-gnu/release/bundle/appimage/rsdk_mod_manager_rs_0.1.0_x86_64.AppImage"

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            target: ${{ matrix.config.target }}

      - name: Install cargo-bundle
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/burtonageo/cargo-bundle

      - name: Run cargo bundle
        if: runner.os != 'Windows'
        uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release --target ${{ matrix.config.target }}

      - name: Run cargo build
        if: runner.os == 'Windows'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.config.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
            name: RSDK Mod Manager Bundles
            path: ${{ matrix.config.path }}
